### ISSUE TITLE
[BUG] Captions causes chat to not work

### ISSUE THREAD

**Issue by Goose441** [bloodycop7/ixehl2rp#9]
[ERROR] gamemodes/ixehl2rp/schema/cl_schema.lua:24: attempt to call field 'AddCaption' (a nil value)
  1. SendCaption - gamemodes/ixehl2rp/schema/cl_schema.lua:24
   2. OnChatAdd - gamemodes/ixehl2rp/schema/sh_schema.lua:284
    3. Send - gamemodes/helix/gamemode/core/libs/sh_chatbox.lua:364
     4. func - gamemodes/helix/gamemode/core/libs/sh_chatbox.lua:386
      5. unknown - lua/includes/extensions/net.lua:38
      
      I've had a few users report that the closed-captions text doesn't work, and instead prevents them from using the chat. (I've not had this issue myself, perhaps a check for if closed captions are nil then end would work.)

**Comment by bloodycop6385** [comment]
Try putting your beta on x64-x86
